stages:
  load_data:
    cmd: python src/data_loader.py data/raw/pricerunner_aggregate.csv data/pre_processed/p
    deps:
    - data/raw/pricerunner_aggregate.csv
    outs:
    - data/pre_processed/pricerunner.csv
  preprocess:
    cmd: python src/processor.py data/pre_processed/pricerunner.csv data/processed/pricerunner.csv
    deps:
    - data/pre_processed/pricerunner.csv
    outs:
    - data/processed/pricerunner.csv
  transform:
    cmd: python src/transformer.py data/processed/pricerunner.csv data/transformed/pricerunner_train_features.csv
      data/transformed/pricerunner_test_features.csv data/transformed/pricerunner_train_target.csv
      data/transformed/pricerunner_test_target.csv
    deps:
    - data/processed/pricerunner.csv
    outs:
    - data/transformed/pricerunner_test_features.csv
    - data/transformed/pricerunner_test_target.csv
    - data/transformed/pricerunner_train_features.csv
    - data/transformed/pricerunner_train_target.csv
  download_model:
    cmd: python src/model_downloader.py && mv src/cc.en.300.bin data/model/cc.en.300.bin
      && rm src/cc.en.300.bin & rm src/cc.en.300.bin.gz
    outs:
    - data/model/cc.en.300.bin
  embedder_train:
    cmd: python src/embedder.py data/transformed/pricerunner_train_features.csv data/final/train.csv
      data/model/cc.en.300.bin
    deps:
    - data/model/cc.en.300.bin
    - data/transformed/pricerunner_train_features.csv
    outs:
    - data/final/train.csv
  embedder_test:
    cmd: python src/embedder.py data/transformed/pricerunner_train_features.csv data/final/train.csv
      data/model/cc.en.300.bin
    deps:
    - data/model/cc.en.300.bin
    - data/transformed/pricerunner_test_features.csv
    outs:
    - data/final/test.csv
