stages:
  load_data:
    cmd: python -m mlops.stages.load_data --config config.yaml
    deps:
    - mlops/stages/load_data.py
    - data/raw/pricerunner_aggregate.csv
    params:
    - config.yaml:
      - load_data
    outs:
    - data/interim/intern.csv

  preprocess_data:
    cmd: python -m mlops.stages.preprocess_data --config config.yaml
    deps:
    - mlops/stages/preprocess_data.py
    - data/interim/intern.csv
    params:
    - config.yaml:
      - preprocess_data
      - load_data
    outs:
    - data/processed/processed.csv

  transform_data:
    cmd: python -m mlops.stages.transform_data --config config.yaml
    deps:
    - mlops/stages/transform_data.py
    - data/processed/processed.csv
    params:
    - config.yaml:
      - transform_data
      - preprocess_data
    outs:
    - data/transformed/test_vocab.csv
    - data/transformed/test.csv
    - data/transformed/train_vocab.csv
    - data/transformed/train.csv

  train:
    cmd: python -m mlops.stages.train --config config.yaml
    deps:
    - mlops/stages/train.py
    - data/transformed/train.csv
    params:
    - config.yaml:
      - train
      - transform_data
    outs:
    - models/model.joblib
    - reports/figures/cm.png

  evaluate:
    cmd: python -m mlops.stages.evaluate --config config.yaml
    deps:
    - mlops/stages/evaluate.py
    - data/transformed/test.csv
    - models/model.joblib
    params:
    - config.yaml:
      - evaluate
      - train
    outs:
    - reports/metrics/metrics.json
    - reports/figures/cm_test.png

  